title: "[Metodo] Scelta metodologica"
body:
  - type: markdown
    attributes:
      value: |
        Usa questo template per discutere scelte metodologiche prima di implementarle.

  - type: textarea
    id: contesto
    attributes:
      label: 🧩 Contesto
      required: true

  - type: textarea
    id: scelta
    attributes:
      label: ⚙ Proposta metodologica

  - type: textarea
    id: alternative
    attributes:
      label: 🔄 Alternative valutate

  - type: textarea
    id: impatto
    attributes:
      label: 📊 Impatto su replicabilità e confronto
